#!/usr/bin/env bash

## This script was auto-generated to clone the selected repositories.
## Keep it secret – it contains your GitHub token.
## Place this script in the folder where you want the repos to live and run it there.

# Default concurrency (override via env: CONCURRENCY=20 ./clone_selected_repos.sh)
CONCURRENCY="${CONCURRENCY:-10}"

githubHost="github.com"
GITHUB_TOKEN="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"

if [ -z "$GITHUB_TOKEN" ]; then
  echo "⛔ GITHUB_TOKEN is empty. Edit this script and set it to a valid GitHub token."
  exit 1
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
cd "$script_dir" || exit 1

echo "⚙️ Using concurrency: ${CONCURRENCY}"

repos=(
  "codeliver-panel-fetch-devices"
  "codeliver-sap-fetch-delivery-devices"
  "codeliver-sap-fetch-stores"
  "codeliver-panel-reorder-zones"
  "codeliver-panel-handle-group-zone"
  "codeliver-panel-handle-delivery-guy-shift"
  "codeliver-panel-fetch-group-zones"
  "codeliver-panel-fetch-group-stores"
  "codeliver-panel-fetch-delivery-guys-actions"
  "codeliver-panel-fetch-delivery-guys"
  "codeliver-panel-fetch-delivery-guy-path"
  "codeliver-panel-device-send-cloud-command"
  "codeliver-fetch-delivery-guy-raw-coordinates"
  "codeliver-sap-fetch-delivery-guys"
  "codeliver-sap-handle-delivery-guy"
  "codeliver-sap-users-stream-ws"
  "codeliver-routes-stream-ws"
  "codeliver-routes-paths-stream-ws"
  "codeliver-routes-paths-stream-update-routes-requests-paths"
  "codeliver-routes-paths-calculations-stream-update-routes-paths"
  "codeliver-requests-calculations-stream-update-requests"
  "codeliver-pos-users-stream-ws"
  "codeliver-panel-stores-stream-ws"
  "codeliver-panel-users-streams-ws"
  "codeliver-panel-group-zones-stream-ws"
  "codeliver-panel-delivery-guys-stream-ws"
  "codeliver-notifications-stream-ws"
  "codeliver-localservers-stream-ws"
  "codeliver-localserver-stream-localserverws"
  "codeliver-groups-stream-ws"
  "codeliver-delivery-requests-stream-ws"
  "codeliver-delivery-guys-coordinates-stream-update-routes-paths"
  "codeliver-delivery-guy-coordinates-stream-ws"
  "codeliver-delete-localserver-logs-stream"
  "codeliver-customers-stream-ws"
  "codeliver-charges-stream-ws"
  "codeliver-sockets-kinesis-consumer"
  "codeliver-request-screenshot-lambda"
  "codeliver-app-sync-actions"
  "codeliver-app-async-actions"
  "codeliver-app-fetch-notifications"
  "codeliver-app-fetch-delivery-guy-path"
  "codeliver-app-delivery-guys-actions-handler"
  "codeliver-app-authorizer"
  "codeliver-apifon-webhook"
  "codeliver-delivery-guys-coordinates-sqs-trigger"
  "codeliver-panel-handle-panel-user"
  "codeliver-panel-handle-device"
  "codeliver-panel-handle-delivery-request"
  "codeliver-sap-socket-emitter-sqs"
  "codeliver-pos-socket-emitter-sqs"
  "codeliver-panel-socket-emitter-sqs"
  "codeliver-app-socket-emitter-sqs"
  "codeliver-create-external-request"
  "codeliver-app-login-mobile-pin"
  "codeliver-app-device-login"
  "codeliver-app-renew-device-token"
  "codeliver-pos-handle-delivery-request"
  "codeliver-sap-handle-group"
  "codeliver-sap-handle-upload"
  "codeliver-fetch-road-path"
  "codeliver-get-delivery-guy-path"
  "codeliver-panel-send-user-credentials"
  "codeliver-pos-user-remind-password"
  "codeliver-test-push-notification"
  "codeliver-routes-merge"
  "codeliver-delivery-request-directions"
  "codeliver-external-precalculate-request"
  "codeliver-panel-search-group-delivery-requests"
  "codeliver-pos-search-delivery-requests"
  "codeliver-panel-handle-delivery-guy"
  "codeliver-app-fetch-delivery-guy-data"
  "codeliver-send-firebase-push-notification"
  "codeliver-recalculate-route-and-paths-distances-and-polylines"
  "codeliver-pos-ws-connect"
  "codeliver-panel-fetch-orphan-localservers"
  "codeliver-panel-fetch-panel-users"
  "codeliver-sap-login"
  "codeliver-panel-get-store-stats-devices"
  "codeliver-sap-handle-user"
  "codeliver-send-sms-gateway"
  "codeliver-delivery-request-estimation"
  "codeliver-sap-renew-token"
  "codeliver-localserver-ws-connect-group-store"
  "codeliver-localserver-ws-connect"
  "codeliver-app-ws-disconnect"
  "codeliver-group-requests-simulation"
  "codeliver-sap-user-remind-password"
  "codeliver-panel-fetch-routes"
  "init-codeliver-superadmin"
  "codeliver-socket-emitter-sqs"
  "codeliver-sms-sqs-dispatcher"
  "codeliver-serverless-check-store-online"
  "codeliver-send-cloud-command"
  "codeliver-sap-send-user-credentials"
  "codeliver-sap-fetch-users"
  "codeliver-sap-authorizer"
  "codeliver-pos-save-localserver-data"
  "codeliver-pos-get-localserver-data"
  "codeliver-panel-ws-disconnect"
  "codeliver-panel-ws-connect"
  "codeliver-panel-ws-cloud-command-response"
  "codeliver-panel-send-user-cloud-command"
  "codeliver-panel-send-cloud-command"
  "codeliver-panel-search-notifications"
  "codeliver-panel-search-localserver-logs"
  "codeliver-panel-search-group-delivery-customers"
  "codeliver-panel-search-group-charges"
  "codeliver-panel-reorder-stores"
  "codeliver-panel-reorder-delivery-guys"
  "codeliver-panel-renew-token"
  "codeliver-panel-login"
  "codeliver-panel-localserver-remote-login"
  "codeliver-panel-handle-store"
  "codeliver-panel-handle-pos-user"
  "codeliver-panel-handle-localserver"
  "codeliver-panel-handle-group"
  "codeliver-panel-handle-delivery-customer"
  "codeliver-panel-get-requests-stats"
  "codeliver-panel-fetch-users-sockets"
  "codeliver-panel-fetch-pos-users-sockets"
  "codeliver-panel-fetch-pos-users"
  "codeliver-panel-fetch-localservers"
  "codeliver-panel-fetch-localserver-sockets"
  "codeliver-panel-fetch-localserver-logs"
  "codeliver-panel-fetch-devices-sockets"
  "codeliver-panel-fetch-delivery-requests-actions"
  "codeliver-panel-fetch-delivery-guys-positions"
  "codeliver-panel-disconnect-user"
  "codeliver-panel-devices-stream-ws"
  "codeliver-panel-delivery-request-calculations"
  "codeliver-panel-connectivity-stats"
  "codeliver-panel-authorizer"
  "codeliver-localservers-socket-pings-sqs-trigger"
  "codeliver-localservers-pings-sqs-trigger"
  "codeliver-localserver-ws-ping"
  "codeliver-localserver-ws-log"
  "codeliver-localserver-ws-disconnect"
  "codeliver-localserver-ws-cloud-command-response"
  "codeliver-localserver-logs-handler"
  "codeliver-init-short-order-id"
  "codeliver-group-data-simulation"
  "codeliver-external-request-pickup-ready"
  "codeliver-delivery-request-actions"
  "codeliver-check-available-delivery-guys-gps-data"
  "codeliver-charge-service"
  "codeliver-backend-check-delivery-requests"
  "codeliver-app-ws-connect"
  "codeliver-app-send-android-id"
  "codeliver-app-get-requests-stats"
  "codeliver-app-fetch-delivery-requests"
  "codeliver-apifon"
  "codeliver-sap-ws-disconnect"
  "codeliver-sap-ws-connect"
  "codeliver-sap-ws-cloud-command-response"
  "codeliver-pos-ws-disconnect"
  "codeliver-pos-send-user-cloud-command"
  "codeliver-pos-renew-token"
  "codeliver-panel-handle-route"
  "codeliver-serverless-restart-browser"
  "codeliver-script-save-groupapp"
  "codeliver-pos-handle-customer"
  "codeliver-pos-get-store"
  "codeliver-pos-get-request-image-raster"
  "codeliver-panel-send-delivery-guy-credentials"
  "codeliver-auto-create-route"
  "codeliver-dispatch-routes-merge"
  "codeliver-dispatch-routes-calculations-merge"
  "codeliver-dispatch-recalculate-route-manual-accept-delivery-guy"
  "codeliver-dispatch-recalculate-route-auto-assign-delivery-guy"
  "codeliver-routes-calculations-merge"
  "codeliver-app-fetch-routes-paths-calculations"
  "codeliver-app-fetch-routes"
  "codeliver-app-fetch-routes-paths"
  "codeliver-pos-handle-store"
  "codeliver-pos-login"
  "codeliver-pos-fetch-routes-paths"
  "codeliver-panel-fetch-routes-paths"
  "codeliver-pos-authorizer"
  "codeliver-panel-fetch-charges"
  "codeliver-innosetup-server"
  "codeliver-handle-aws-df-cloud-resource"
  "codeliver-pos-ws-cloud-command-response"
  "codeliver-sap-fetch-admin-sockets"
  "codeliver-panel-delivery-request-recalculate-estimation"
  "codeliver-panel-check-autocomplete-address"
  "codeliver-manually-dispatch-delivery-guy"
  "codeliver-init-panel-superadmin-users"
  "codeliver-get-zone-average-times"
  "codeliver-dispatch-route-manual-accept-delivery-guy"
  "codeliver-dispatch-route-auto-assign-delivery-guy"
  "codeliver-check-address-areas"
  "codeliver-app-handle-route"
  "codeliver-app-remind-password"
  "codeliver-app-handle-delivery-guy"
  "codeliver-pos-fetch-delivery-requests"
  "codeliver-panel-user-remind-password"
  "codeliver-retry-failed-db-stream"
  "codeliver-pos-send-cloud-command"
  "codeliver-script-get-groupapp"
  "codeliver-pos-check-autocomplete-address"
  "codeliver-sap-get-store-data"
  "codeliver-panel-get-store"
  "codeliver-requests-print-stream"
  "codeliver-requests-dm-stream"
  "codeliver-panel-recalculate-distance"
  "codeliver-panel-get-group"
  "codeliver-panel-fetch-notifications"
  "codeliver-panel-get-store-devices"
  "codeliver-pos-search-customer"
  "codeliver-panel-manually-dispatch-delivery-guy"
  "codeliver-sap-fetch-groups"
  "codeliver-sap-save-store-data"
  "codeliver-users-stream-ws"
  "codeliver-pos-stores-stream-ws"
  "codeliver-panel-search-store-customer"
  "codeliver-panel-fetch-routes-paths-calculations"
  "codeliver-sap-create-new-store"
  "codelivery-sap-handle-upload"
  "codeliver-panel-search-delivery-requests"
  "codeliver-panel-fetch-delivery-requests"
  "codeliver-devices-sockets-stream-ws"
  "codeliver-sap-fetch-delivery-devices-sockets"
  "codeliver-sap-fetch-delivery-requests"
  "codeliver-sap-handle-delivery-request"
  "codeliver-sap-get-delivery-request"
  "codeliver-recursive-data-simulation"
  "codeliver-panel-fetch-group-delivery-requests"
  "codeliver-panel-check-calculations-history"
  "codeliver-panel-delivery-request-dispatch-calculations"
  "codeliver-panel-create-store"
  "codeliver-panel-create-delivery-request"
  "codeliver-check-future-dispatch-requests-sqs-trigger"
  "codeliver-check-future-dispatch-requests"
  "codeliver-panel-make-delivery-request-calculations"
  "codeliver-panel-dispatch-delivery-guy"
  "codeliver-dispatch-delivery-guy"
  "codeliver-panel-fetch-delivery-guys-sockets"
  "codeliver-cost-wizard-react"
  "codeliver-cost-calculator"
  "codeliver-website"
  "codeliver-app-handle-route-path"
  "codeliver-panel-handle-route-path"
  "codeliver-panel-search-routes-paths"
  "codeliver-panel-search-routes"
  "dm-codeliver-webhook"
  "dm-codeliver-precalculate-request"
  "codeliver-localserver-x64"
  "codeliver-monitor-localserver-x64"
  "codeliver-image-templates-app"
  "codeliver-s3-sqs-socket-pings-emitter"
  "codeliver-panel-delivery-guys-positions"
  "codeliver-pos-fetch-customers"
  "codeliver-users-streams-ws"
  "codeliver-dispatch-recalculate-route-maunal-accept-delivery-guy"
  "codeliver-batches-stream-ws"
  "codeliver-routes-stream-update-routes-sqs-trigger"
  "codeliver-create-routes-orchestrator"
  "codeliver-sap-handle-store"
  "codeliver-pos-fetch-routes"
  "codeliver-pos-fetch-zones"
  "codeliver-pos-fetch-delivery-guys-positions"
  "codeliver-pos-fetch-delivery-guys"
  "codeliver-pos-fetch-delivery-guy-path"
  "codeliver-pos-search-customers"
  "codeliver-pos-fetch-requests-actions"
  "codeliver-routes-paths-stream-update-routes-sqs-trigger"
  "codeliver-pos-fetch-routes-paths-calculations"
  "codeliver-pos-handle-device"
  "codeliver-pos-fetch-devices"
  "codeliver-create-routes"
  "codeliver-pos-fetch-devices-sockets"
  "codeliver-pos-handle-delivery-guy"
  "codeliver-pos-fetch-stores"
  "codeliver-pos-fetch-requests-calculations"
  "codeliver-pos-fetch-delivery-guy-raw-coordinates"
  "codeliver-pos-device-send-cloud-command"
  "codeliver-pos-handle-delivery-guy-shift"
  "codeliver-pos-fetch-delivery-guys-actions"
  "codeliver-pos-send-delivery-guy-credentials"
  "codeliver-pos-test-push-notification"
  "codeliver-routes-paths-stream-update-routes-sqs"
  "codeliver-sap-reorder-zones"
  "codeliver-sap-handle-zone"
  "codeliver-sap-fetch-zones"
  "codeliver-panel-fetch-batches"
  "codeliver-sap-handle-panel-user"
  "codeliver-sap-fetch-panel-users"
  "codeliver-fix-requests-delivery-stats"
  "codeliver-sap-fetch-panel-users-sockets"
  "codeliver-sap-fetch-localservers"
  "codeliver-website-form-submit"
  "codeliver-routes-stream-update-notifications"
  "codeliver-io"
  "codeliver-sap-fetch-users-sockets"
  "codeliver-pos-handle-route"
  "codeliver-app-register-push-token"
  "codeliver-sap-fetch-delivery-guys-actions"
  "codeliver-sap-handle-delivery-guy-shift"
  "codeliver-sap-fetch-delivery-guy-raw-coordinates"
  "codeliver-sap-fetch-delivery-guy-path"
  "codeliver-sap-fetch-batches"
  "codeliver-sap-device-send-cloud-command"
  "codeliver-sap-handle-device"
  "codeliver-sap-fetch-pos-users-sockets"
  "codeliver-sap-fetch-pos-users"
  "codeliver-sap-handle-pos-user"
  "codeliver-sap-reorder-stores"
)

clone_repo() {
  local fullName="$1"
  local repoDir="${fullName##*/}"

  if [ -d "$repoDir/.git" ]; then
    echo "✅ Skipping ${fullName}: already cloned in ${repoDir}"
    return 0
  fi
  if [ -d "$repoDir" ]; then
    echo "⚠️ Skipping ${fullName}: directory ${repoDir} exists but is not a git repo."
    return 0
  fi

  echo "🌀 Cloning ${fullName} ..."
  if git clone "https://${GITHUB_TOKEN}@${githubHost}/dmngr/${fullName}.git"; then
    echo "✅ Done ${fullName}"
  else
    echo "⛔ Failed ${fullName}" >&2
    return 1
  fi
}

export -f clone_repo
export githubHost
export GITHUB_TOKEN

printf "%s\0" "${repos[@]}" | xargs -0 -n 1 -P "$CONCURRENCY" -I {} bash -c 'clone_repo "$1"' _ {}

echo "All done!"